name: CI for Org File Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  qt6-qtbase-devel qt6-qmake gcc-c++ make
      
      - name: Build
        run: |
          qmake
          make -j8
      
