name: CI for Org File Manager

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Qt environment
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.0' # Adjust this to the Qt version you're using
          modules: qtbase,qttools # Include other modules if necessary

      # Step 3: Install build tools
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      # Step 4: Configure the build
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. # Add additional flags if necessary

      # Step 5: Build the project
      - name: Build
        run: |
          cd build
          cmake --build .

      # Step 6: Run tests (optional)
      - name: Run Tests
        run: |
          cd build
          ctest
