name: CI for Org File Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.7.2' 
          modules: qtbase,qttools 

   
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      
      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. # Add additional flags if necessary

    
      - name: Build
        run: |
          cd build
          cmake --build .

      
      - name: Run Tests
        run: |
          cd build
          ctest
