name: CI for Org File Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip build-essential cmake

      - name: Install AQT
        run: |
          python3 -m pip install aqtinstall

      - name: List available Qt modules
        run: |
          python3 -m aqt list-qt linux desktop --modules 6.2.0 x86_64

      - name: Install Qt with AQT
        run: |
          python3 -m aqt install-qt 6.5.2 linux desktop -m qtbase,qttools -O /home/runner/work/org/Qt

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. 

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest
